// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxAK4tqvOnoLMbaRPzTGuDXPhvMpkYKnM',
    appId: '1:941468211973:web:e0091ca12fd2fc0886b56c',
    messagingSenderId: '941468211973',
    projectId: 'money-manager100',
    authDomain: 'money-manager100.firebaseapp.com',
    storageBucket: 'money-manager100.firebasestorage.app',
    measurementId: 'G-ESSEZHJLQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvHgJYvQP6-JMMHgK2q-Ehyuj5qcby-P8',
    appId: '1:941468211973:android:b50e90a47085298686b56c',
    messagingSenderId: '941468211973',
    projectId: 'money-manager100',
    storageBucket: 'money-manager100.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXK6AuVG3BoIJm6A7kGHEwyNeMjkd-Eok',
    appId: '1:941468211973:ios:860cdeec7b47432d86b56c',
    messagingSenderId: '941468211973',
    projectId: 'money-manager100',
    storageBucket: 'money-manager100.firebasestorage.app',
    iosBundleId: 'com.example.moneyManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxAK4tqvOnoLMbaRPzTGuDXPhvMpkYKnM',
    appId: '1:941468211973:web:a4e2175b1cd962e886b56c',
    messagingSenderId: '941468211973',
    projectId: 'money-manager100',
    authDomain: 'money-manager100.firebaseapp.com',
    storageBucket: 'money-manager100.firebasestorage.app',
    measurementId: 'G-YDHSM8G0T9',
  );
}
